version: '3'

services:
  postgres:
    image: 'postgres:17-alpine'
    hostname: postgres-server
    ports:
      - '15432:5432'
    env_file:
      - .env
    networks:
      - db-network
    volumes:
      - ${PWD}/pg-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin-web
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - db-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/
    user: '$UID:$GID'

networks:
  db-network:
    driver: bridge
